// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaFNqNcdQicg1LNFiD2e96_oSpZ6tYtI',
    appId: '1:217981352155:web:8704a36e06f0b6b39bf4fe',
    messagingSenderId: '217981352155',
    projectId: 'trackdeed-7436d',
    authDomain: 'trackdeed-7436d.firebaseapp.com',
    storageBucket: 'trackdeed-7436d.firebasestorage.app',
    measurementId: 'G-J6LMZHNYQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRY1zM6muX1aKw_2B9i20wOlAyW-zV50k',
    appId: '1:217981352155:android:4b08e6594cd0cf419bf4fe',
    messagingSenderId: '217981352155',
    projectId: 'trackdeed-7436d',
    storageBucket: 'trackdeed-7436d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPaFNqNcdQicg1LNFiD2e96_oSpZ6tYtI',
    appId: '1:217981352155:web:19a73333a76d81cb9bf4fe',
    messagingSenderId: '217981352155',
    projectId: 'trackdeed-7436d',
    authDomain: 'trackdeed-7436d.firebaseapp.com',
    storageBucket: 'trackdeed-7436d.firebasestorage.app',
    measurementId: 'G-LXZJGRLEQT',
  );
}
